[project]
name = "arxiv_cleaner"
version = "0.1.0"
dependencies = [
    "argparse",
    "pathlib",
    "logging"
]

[build-system]
requires = ["setuptools>=61.0"]
build-backend = "setuptools.build_meta"

[tool.setuptools]
packages = ["arxiv_cleaner"]